# Generated by Django 3.1.7 on 2021-03-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20210304_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centre',
            name='department_number',
            field=models.IntegerField(null=True),
        ),
    ]
