# Generated by Django 3.1.7 on 2021-03-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_check', models.DateTimeField(null=True)),
                ('last_availability', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('last_notification', models.DateTimeField(null=True)),
                ('subscriptions', models.ManyToManyField(related_name='subscriber', to='telegram_bot.Centre')),
            ],
        ),
    ]
