# Generated by Django 3.1.7 on 2021-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegram_bot', '0002_auto_20210303_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='centre',
            name='reservation_url',
            field=models.URLField(default='https://www.doctolib.fr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centre',
            name='last_check',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_notification',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
